:javascripts:
  - public/javascripts/vendor/underscore/underscore.js
  - public/javascripts/vendor/*.js
  - public/javascripts/application.js
  - public/javascripts/lib/bindable.js
  - public/javascripts/lib/set.js
  - public/javascripts/lib/*.js
  - public/javascripts/**/*.js

:stylesheets:
  - public/stylesheets/reset.css
  - public/stylesheets/aristo.css
  - public/stylesheets/*.css
