javascript_compressor: closure
template_function: _.template
embed_assets: on

javascripts:
  v1:
    - public/javascripts/application.js
    - public/javascripts/vendor/jquery-1.3.2.js
    - public/javascripts/vendor/*.js
    - public/javascripts/lib/bindable.js
    - public/javascripts/lib/set.js
    - public/javascripts/lib/*.js
    - public/javascripts/model/*.js
    - public/javascripts/v1/ui/common/*.js
    - public/javascripts/v1/**/*.js
  ie_only:
    - public/javascripts/ie/*.js

stylesheets:
  v1:
    - public/stylesheets/common/reset.css
    - public/stylesheets/v1/aristo.css
    - public/stylesheets/v1/*.css
  v1_workspace:
    - public/stylesheets/pages/workspace.css
  empty:
    - public/stylesheets/pages/empty.css
  docs:
    - public/stylesheets/pages/docs.css
  static:
    - public/stylesheets/common/reset.css
    - public/stylesheets/pages/static.css
  viewer_editing:
    - public/stylesheets/v1/ui.css
    - public/stylesheets/v1/icons.css
    - public/stylesheets/pages/viewer_editing.css

templates:
  v1:
    - app/views/jst/v1/**/*.jst
