javascript_compressor: closure
template_function: _.template
embed_images: on

javascripts:
  workspace:
    - public/javascripts/application.js
    - public/javascripts/vendor/*.js
    - public/javascripts/lib/bindable.js
    - public/javascripts/lib/set.js
    - public/javascripts/lib/*.js
    - public/javascripts/ui/menu.js
    - public/javascripts/**/*.js

stylesheets:
  app:
    - public/stylesheets/reset.css
    - public/stylesheets/aristo.css
    - public/stylesheets/*.css
  workspace:
    - public/stylesheets/pages/workspace.css
  empty:
    - public/stylesheets/pages/empty.css
  docs:
    - public/stylesheets/pages/docs.css

templates:
  complete:
    - app/views/jst/**/*.jst
