defaults: &defaults
  adapter:  postgresql
  encoding: unicode
  pool:     5
  username: REDACTED
  password: REDACTED
  
# Main Database.

development:
  <<: *defaults
  database: dcloud_main_development

staging:
  <<: *defaults
  database: dcloud_main_staging

test:
  <<: *defaults
  database: dcloud_main_test
  
# Document Database.
  
docs_development:
  <<: *defaults
  database: dcloud_docs_development

docs_staging:
  <<: *defaults
  database: dcloud_docs_staging
  
docs_test:
  <<: *defaults
  database: dcloud_docs_test