defaults: &defaults
  adapter: postgresql
  encoding: unicode
  schema_search_path: public
  pool:     5
  username: REDACTED
  password: REDACTED
  allow_concurrency: true

development:
  <<: *defaults
  database: dcloud_development

staging:
  <<: *defaults
  host: staging.dcloud.org
  database: dcloud_staging

test:
  <<: *defaults
  database: dcloud_test
