# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

development:
  adapter:  mysql
  encoding: utf8
  username: root
  password:
  socket:   /tmp/mysql.sock
  database: dcloud_main_development

staging:
  adapter:  mysql
  encoding: utf8
  username: root
  password:
  socket:   /var/run/mysqld/mysqld.sock
  database: dcloud_main_staging

test:
  adapter:  mysql
  encoding: utf8
  username: root
  password:
  socket:   /tmp/mysql.sock
  database: dcloud_main_test