<% secrets = YAML.load_file('config/secrets.yml')[ENV['RAILS_ENV']] %>

defaults: &defaults
  adapter: postgresql
  encoding: unicode
  schema_search_path: public
  username: <%= secrets['username'] %>
  password: <%= secrets['db_password'] %>
  allow_concurrency: true

development:
  <<: *defaults
  database: dcloud_development

staging:
  <<: *defaults
  host: staging.dcloud.org
  database: dcloud_staging

production:
  <<: *defaults
  host: ec2-174-129-5-5.compute-1.amazonaws.com
  database: dcloud_production

test:
  <<: *defaults
  database: dcloud_test
