defaults: &defaults
  cloud_crowd_server:   http://dev.dcloud.org:8080
  server_root:          http://dev.dcloud.org
  aws_zone:             us-east-1c
  preconfigured_ami_id: ami-f94ca390

  # Include Postgres-generated highlights of the search query within the
  # document results (too slow).
  include_highlights:   off


development:
  <<: *defaults

staging:
  <<: *defaults
  cloud_crowd_server: http://staging.dcloud.org:8080
  server_root:        http://staging.dcloud.org

production:
  <<: *defaults
  cloud_crowd_server: http://ec2-174-129-5-5.compute-1.amazonaws.com:8080
  server_root:        http://www.documentcloud.org
  db_volume_id:       vol-d4c305bd

test:
  <<: *defaults