defaults: &defaults
  cloud_crowd_server: http://dev.dcloud.org:8080
  server_root:        http://dev.dcloud.org
  include_highlights: off
  aws_zone: us-east-1c
  preconfigured_ami_id: ami-f4db369d

development:
  <<: *defaults

staging:
  <<: *defaults
  cloud_crowd_server: http://staging.dcloud.org:8080
  server_root:        http://staging.dcloud.org

production:
  <<: *defaults
  cloud_crowd_server: http://ec2-174-129-5-5.compute-1.amazonaws.com:8080
  server_root:        http://production.dcloud.org

test:
  <<: *defaults