defaults: &defaults
  cloud_crowd_server:   http://dev.dcloud.org:8080
  server_root:          dev.dcloud.org
  aws_zone:             us-east-1c
  preconfigured_ami_id: ami-3bad6752

development:
  <<: *defaults

staging:
  <<: *defaults
  cloud_crowd_server: http://staging.documentcloud.org:8080
  server_root:        staging.documentcloud.org

production:
  <<: *defaults
  cloud_crowd_server: http://ec2-174-129-5-5.compute-1.amazonaws.com:8080
  server_root:        www.documentcloud.org
  db_volume_id:       vol-d4c305bd

test:
  <<: *defaults