defaults: &defaults
  cloud_crowd_server:   http://localhost:9173
  server_root:          http://localhost:3000
  entry_store_port:     70007
  metadata_store_port:  80008
  
development:
  <<: *defaults
  
staging:
  <<: *defaults
  cloud_crowd_server:   http://staging.dcloud.org:9173
  server_root:          http://staging.dcloud.org
  
test:
  <<: *defaults
    
production:
  <<: *defaults