defaults: &defaults
  cloud_crowd_server: http://dev.dcloud.org:9173
  server_root:        http://dev.dcloud.org

development:
  <<: *defaults

staging:
  <<: *defaults
  cloud_crowd_server: http://staging.dcloud.org:8080
  server_root:        http://staging.dcloud.org

test:
  <<: *defaults

production:
  <<: *defaults