defaults: &defaults
  cloud_crowd_server: http://dev.dcloud.org:8080
  server_root:        http://dev.dcloud.org
  include_highlights: off

development:
  <<: *defaults

staging:
  <<: *defaults
  cloud_crowd_server: http://staging.dcloud.org:8080
  server_root:        http://staging.dcloud.org

production:
  <<: *defaults
  cloud_crowd_server: http://174.129.5.5:8080
  server_root:        http://production.dcloud.org

test:
  <<: *defaults