<% secrets = YAML.load_file(File.join(Rails.root, 'secrets/secrets.yml'))[ENV['RAILS_ENV'] || 'development'] %>

development:
  auto_commit_after_request: false
  solr:
    hostname: localhost
    port: 7377
    log_level: INFO
    min_memory: 20M
    max_memory: 500M
    solr_jar: vendor/solr-3.4.0/start.jar
  
staging:
  auto_commit_after_request: false
  solr:
    hostname: <%= secrets['solr_host'] %>
    port: 7377
    log_level: WARNING
    solr_jar: vendor/solr-3.4.0/start.jar

production:
  auto_commit_after_request: false
  solr:
    hostname: <%= secrets['solr_host'] %>
    port: 7377
    log_level: INFO
    min_memory: 200M
    max_memory: 1500M
    solr_jar: vendor/solr-3.4.0/start.jar

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
