# This is a standard ActiveRecord database.yml file. You can configure it
# to use any database that ActiveRecord supports.

:adapter:  postgresql
:encoding: unicode
:schema_search_path: public
:pool:     5
:username: REDACTED
:password: REDACTED
:allow_concurrency: true
:host:     174.129.5.5
:database: dcloud_crowd_production
